project:
  type: website
  output-dir: docs

website:
  title: "Leandra Purvis"
  navbar:
    left:
      - href: Index Page.qmd
        text: Home
      - href: https://drive.google.com/file/d/1wXQc20oYHY1mhGNRCFdPFt4UnzTNGnuS/view?usp=sharing
        text: Resume
      - Portfolio.qmd
      - Walkthrough.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true