---
title: "Covid Memorial"
---

*Covid Memorial* takes a look at a site setup on the national mall to honor the lives of those lost to the Covid-19 pandemic.

In the spring of 1963 Yoko Ono wrote a piece entitled "Cloud Piece".

*Imagine the clouds dripping. Dig a hole in your garden to put them in.*

Looking out across the expanse of the National Mall, it looked as though someone had opened a hole for fallen clouds. Seemingly endless fields of nearly blinding, sparkling white, in front of the Washington Monument. Only when approached can one begin to distinguish the small shapes from one another.

White flags, thousands of them, placed individually and orderly in differently shaped patches. Surrounding and in between the patches of white were tourists and visitors. Couples embracing or taking selfies to capture the moment. Families with parents running after their children attempting to corral and control them. Photographers setup with their gear and tripods attempting to capture the energy of it all. And every now and then, someone crouching to place a flag of their own.

Every flag placed represents a loved one lost to COVID-19. On some flags there are even messages and names written.

*We love and miss you everyday... Can't wait to see you again in heaven*

But as it is in most touristy areas, the memorial mostly serves as another stop on a traveler's itinerary of sights to see. Being in front of a historic monument, the memorial lends itself to a great bustling of sight-seers moving through and in between the flags. It creates a hum of noise to contrast or maybe accompany the memory of those lost to the illness.

Against the noise, however, there remains a sense of stillness. Looking out upon the field, the eyes are easily drawn to lack of motion. A man crouched on the ground placing his flag and then remaining. Hands planted firmly in the grass, eyes closed, shut out from the rest of the world, he radiated a grief that could be felt from the opposite end. Down another path a woman walked slowly, arms crossed and brows set close together. Her eyes looking downward, she appeared focused on reading the individual messages, recognizing the loss of the lives represented through the white plastic.

Every twenty or thirty feet this pattern repeated: a sprinkle of individuals moving quickly and swiftly around a body crouched in grief. As everyone moves through their days concerned with themselves and their own motives, sometimes the cycle is broken. If only just for a moment, the woman walking, the man crouching, or the visitor simply passing through are pulled out of their world and into the thoughts of another.
