---
title: "Modern Nudity"
---

[*Below is an excerpt of a recent piece I wrote. The full 11 page piece can be found [here](https://docs.google.com/document/d/1H9XLbq6k1mWwQ5a95h8gWKCodv_FFeLA/edit?usp=sharing&ouid=104316388011066606064&rtpof=true&sd=true).*]{.underline}

*Modern Nudity* is a narrative journalism piece that looks at the lives of modern-day art models and how they are perceived by the private eye of the art world, as well as the public.

\-\-\-\-\-\-\-\-\-\-\--

There is a certain feeling one gets when walking through a museum. As my heels clicked rhythmically across the polished floors of the National Gallery of Art, I could feel the weight of centuries of humanity pressing in on me. Under this feeling, I wandered from room to room until I found myself seated on a long wooden bench surrounded by the work of French artist Auguste Renoir. I was in front of *Bather Arranging Her Hair*, in which a young woman standing naked worked to part her hair surrounded by items of clothing. 

I sat to view the painting and rest for a moment, but soon I was more carried away by watching the people who approached the work. "See, these women, they aren't treated as people, they're treated as little *things* to paint", a young woman stated to her friends in a matter-of-fact tone as they stood around it. Shortly after, a teenage girl holding hands with her partner approached. They stood for just a moment, then snapped a photo before continuing their stroll. 

After sitting for a bit, I straightened myself and began wandering again until I landed in front of another nude study. In the National Gallery of Art, it is assumed that nude portraiture, both male and female, will be looked at with appreciation. I watched group after group walk in front of barely clothed women, pausing for a moment or two to let their eyes wander over the painted figures. Some remarked how brilliant the technique or some other aspect was, others stood in silence, and some merely stopped for a second, eyes fleeting around the work and then moving along. 

Yet, as I watched these people examine the portraits, I never once heard a comment in the vein of *she should leave more to the imagination*, or *I can't believe they would allow themselves to be seen publicly like that*. Shame is not tied to the "classical" nude portrait as it is to nudity in modern society. A model told me once that whereas in the art community his nudity is viewed as a necessity, in the real world it is viewed as taboo. 

As my heels echoed through the galleries, I ruminated on this idea. Does the impact of the naked figure vary based on its context? Throughout history, models who sat for artists were regarded from one extreme to the other. In the Renaissance, to be the muse of an artist was seen as a great privilege. Two centuries later the sitting model was seen as nothing more than a prostitute. I wondered if it was just the lens I was viewing it through. Even further than that, I wondered what it was like to sit for an artist in today's age. 

\-\-\-\-\-\-\-\-\-\-\--

Models, in their own time, need to have a conversation with themselves and find where they draw that line. Sometimes that line comes from a predetermined judgment about what the model is and is not willing to do, but sometimes it comes from poor experiences and uncomfortable sessions. A job that pushes comfort levels may pay triple the amount of their regular work; this "temptation" often being the main draw to this type of work according to Avid.

*If you're willing to do almost anything, you can make a lot of money. Models that I know have had to actually stop and say "OK, well, at this point, it's not worth it. Even if I'm making 500 bucks, I'm not, ya know..." And also thinking long term, you don't want to ruin your reputation and become, like, "Oh, you're one of those models" or whatever. I think that's one of the areas where the models in this little collective help each other a lot too, because somebody relatively new may not realize what they're opening themselves up to.*

For Avid, at the end of the day, the models are there for their bodies and to provide a service with them. He sees himself as part of the art-making process, an essential piece of the work. 

\-\-\-\-\-\-\-\-\-\-\--

When a model shows up for a session, general artist etiquette is to understand the model is there for figure reference and they must be treated with respect in that regard. Everything that happens during a session should be decided upon beforehand to ensure that everyone is comfortable. Whether it is a class studying movement or a photography session in a sex dungeon, the model is there to provide a predetermined service and that is all. 

For a while, though, Emily did not have the means, or the "luxury" to turn down sessions and found herself caught in a loop with some disrespectful artists.

*I just felt like, "stop sexualizing me and stop making jokes about your creepy, gross, flattening fantasies." And really, what I meant was, "stop sexualizing me in a way that doesn't include my agency, in a way that doesn't include my consent." Technically, my consent is being used, but it's not my story.* 

This is a common complaint within the modeling community, something both Avid and Emily have experienced and know others have experienced as well. They, as the woman in the art gallery commented, are being treated as objects to paint. This removes the model's voice and autonomy from the work they are taking part in. 

\-\-\-\-\-\-\-\-\-\-\--

No matter the era the art is created, there will always be differing opinions on how the body should be viewed. It raises the question for me: is it fair that the art piece is viewed with awe and admiration if the model is not? And how is that gap bridged? 

    Regardless of the answers to these questions, if there are answers, models will continue to sit for artists, no matter the medium, and inspire them. Avid and Emily will continue to pose and create art, and respond accordingly when people heckle or praise them for their work. The art modeling community is a vibrant place full of people with their own quirks and personalities. This variety helps add to the uniqueness of the pieces we see hanging before us in galleries across the country. Without them, we would not have much of the work we know and love today. 

\
